apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

resources:
- https://github.com/kubernetes-sigs/kustomize//examples/helloWorld?timeout=120&ref=v3.3.1
- ingress.yaml
patches:
- path: configMap.yaml
- path: service.yaml
